import Foundation

@main enum HistoryTests {
    static func main() {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(identifier: "America/New_York")!
        let today = HistoryDates.date(for: "2026-11-10", calendar: calendar)!
        var history = ActivityHistory()
        func expect(_ value: Bool, _ message: String) { precondition(value, message) }
        for offset in 0..<40 {
            let date = calendar.date(byAdding: .day, value: -offset, to: today)!
            let record = DayRecord(day: HistoryDates.key(for: date, calendar: calendar), completed: 1, skipped: 2, postponed: 3, rested: 20)
            history.update(record, now: today, calendar: calendar)
        }
        expect(history.records.count == 30, "Retain exactly today and previous 29 days")
        expect(history.records.first?.day == "2026-10-12", "Calendar-day cutoff includes DST change")
        expect(history.records.last?.day == "2026-11-10", "Include today")
        let total = ActivityHistory.total(history.days(now: today, calendar: calendar))
        expect(total.completed == 30 && total.skipped == 60 && total.postponed == 90 && total.rested == 600, "Totals across days")
        let saved = try! JSONEncoder().encode(history)
        let reloaded = try! JSONDecoder().decode(ActivityHistory.self, from: saved)
        expect(reloaded == history, "History survives restart")
        let changed = DayRecord(day: "2026-11-10", completed: 8, rested: 300)
        history.update(changed, now: today, calendar: calendar)
        expect(history.records.count == 30 && history.records.last == changed, "Updating today replaces instead of duplicating")
        history.migrate(DayRecord(day: "2026-11-10", completed: 999), now: today, calendar: calendar)
        expect(history.records.last == changed, "Legacy migration cannot overwrite persisted history")
        let tomorrow = calendar.date(byAdding: .day, value: 1, to: today)!
        history.update(DayRecord(day: "2026-11-11"), now: tomorrow, calendar: calendar)
        expect(history.records.count == 30 && history.records.first?.day == "2026-10-13", "Prune at midnight without losing yesterday")
        expect(history.records.first(where: { $0.day == "2026-11-10" }) == changed, "Preserve yesterday's completed and rest totals")
        var sparse = ActivityHistory()
        sparse.migrate(DayRecord(day: "2026-11-09", completed: 4, skipped: 1, rested: 120), now: today, calendar: calendar)
        let days = sparse.days(now: today, calendar: calendar)
        expect(days.count == 30 && days[28].completed == 4 && days[29].completed == 0, "Fill unrecorded days with zero values")
        expect(sparse.days(count: 7, now: today, calendar: calendar).count == 7, "Seven-day view")
        sparse.migrate(DayRecord(day: "2020-01-01", completed: 8), now: today, calendar: calendar)
        expect(sparse.records.count == 1, "Discard legacy data outside retention")
        sparse.update(DayRecord(day: "invalid", completed: 8), now: today, calendar: calendar)
        expect(sparse.records.count == 1, "Ignore malformed dates")
        expect(HistoryDates.date(for: "2026-02-30", calendar: calendar) == nil, "Reject normalized invalid dates")
        let legacyData = try! JSONSerialization.data(withJSONObject: ["records": [["day": "2026-11-10", "completed": 2, "skipped": 1, "postponed": 0, "rested": 40]]])
        var timed = try! JSONDecoder().decode(ActivityHistory.self, from: legacyData)
        expect(timed.records[0].completed == 2 && timed.sessions.isEmpty, "Old daily totals migrate without invented timestamps")
        let start = calendar.date(bySettingHour: 10, minute: 23, second: 17, of: today)!
        let id = timed.startSession(planID: UUID(), name: "Quick", duration: 20, at: start, now: start, calendar: calendar)
        expect(timed.sessions.first?.startedAt == start && timed.sessions.first?.outcome == .inProgress, "Persist exact break start immediately")
        let end = start.addingTimeInterval(23.25)
        timed.endSession(id, outcome: .completed, at: end, rested: 20, now: end, calendar: calendar)
        expect(timed.sessions[0].endedAt == end && timed.sessions[0].rested == 20 && timed.sessions[0].name == "Quick", "Preserve exact end, rest, and historical name")
        timed.endSession(id, outcome: .interrupted, at: end.addingTimeInterval(60), now: end, calendar: calendar)
        expect(timed.sessions[0].outcome == .completed && timed.sessions[0].endedAt == end, "A completed session cannot be reclassified on quit")
        for outcome in [BreakOutcome.skipped, .postponed, .interrupted] {
            let event = timed.startSession(planID: UUID(), name: outcome.title, duration: 300, at: start, now: end, calendar: calendar)
            timed.endSession(event, outcome: outcome, at: end, now: end, calendar: calendar)
        }
        let crash = timed.startSession(planID: UUID(), name: "Crash", duration: 300, at: start, now: end, calendar: calendar)
        timed.recoverInterruptedSessions()
        expect(timed.sessions.first(where: { $0.id == crash })?.outcome == .interrupted && timed.sessions.first(where: { $0.id == crash })?.endedAt == nil, "Unclean exit is interrupted without inventing an end time")
        let persisted = try! JSONDecoder().decode(ActivityHistory.self, from: JSONEncoder().encode(timed))
        expect(persisted == timed && persisted.records[0].completed == 2, "Exact sessions survive relaunch without changing daily totals")
        let cutoff = calendar.date(byAdding: .day, value: -29, to: today)!
        let old = timed.startSession(planID: UUID(), name: "Old", duration: 20, at: cutoff.addingTimeInterval(-100), now: start, calendar: calendar)
        expect(!timed.sessions.contains(where: { $0.id == old }), "Prune timestamp history on the same calendar-day boundary")
        var crossing = ActivityHistory()
        let boundary = crossing.startSession(planID: UUID(), name: "Midnight", duration: 300, at: cutoff.addingTimeInterval(-10), now: cutoff.addingTimeInterval(-10), calendar: calendar)
        crossing.endSession(boundary, outcome: .completed, at: cutoff.addingTimeInterval(290), rested: 300, now: start, calendar: calendar)
        expect(crossing.sessions.count == 1 && crossing.sessions[0].startedAt < cutoff, "Retain a break spanning the retention boundary")
        crossing.prune(now: tomorrow, calendar: calendar)
        expect(crossing.sessions.isEmpty, "Remove the boundary-spanning break once its end is outside retention")
        var viewport = ActivityViewport(now: start, calendar: calendar)
        viewport.zoom(to: 1)
        expect(viewport.span == 3600 && viewport.range.contains(start), "Zoom reaches one-hour granularity around the current time")
        viewport.zoom(to: .infinity); expect(viewport.span == 3600, "Ignore invalid zoom inputs")
        viewport.move(to: .distantPast); expect(viewport.range.lowerBound == cutoff, "Pan clamps to oldest retained day")
        viewport.move(to: .distantFuture); expect(viewport.range.upperBound == tomorrow, "Pan clamps to the end of today")
        viewport.zoom(to: 86400 * 40)
        expect(viewport.range == cutoff...tomorrow && viewport.span == 86400 * 30 + 3600, "Full range uses calendar days across daylight-saving change")
        var exact = ActivityHistory()
        let nine = calendar.date(bySettingHour: 9, minute: 0, second: 0, of: today)!
        let complete = exact.startSession(planID: UUID(), name: "Rest", duration: 300, at: nine.addingTimeInterval(13 * 60), now: start, calendar: calendar)
        exact.endSession(complete, outcome: .completed, at: nine.addingTimeInterval(18 * 60), rested: 300, now: start, calendar: calendar)
        let skipped = exact.startSession(planID: UUID(), name: "Skip", duration: 300, at: nine.addingTimeInterval(30 * 60), now: start, calendar: calendar)
        exact.endSession(skipped, outcome: .skipped, at: nine.addingTimeInterval(31 * 60), now: start, calendar: calendar)
        exact.recordAction(.postponed, at: nine.addingTimeInterval(59 * 60), now: start, calendar: calendar)
        exact.recordAction(.skipped, at: nine.addingTimeInterval(60 * 60), now: start, calendar: calendar)
        let interrupted = exact.startSession(planID: UUID(), name: "Interrupted", duration: 300, at: nine, now: start, calendar: calendar)
        exact.endSession(interrupted, outcome: .interrupted, at: nine.addingTimeInterval(10), now: start, calendar: calendar)
        let hour = exact.buckets(in: nine...nine.addingTimeInterval(3600), calendar: calendar)
        expect(hour.count == 4 && hour[0].totals.outcomes == 0 && hour[1].totals.completed == 1 && hour[1].totals.rested == 300, "Quarter-hour bins credit rest at completion, not at the start")
        expect(hour[2].totals.skipped == 1 && hour[3].totals.postponed == 1, "Active and future-break actions appear exactly once at their real times")
        expect(ActivityHistory.total(hour.map { $0.totals }).outcomes == 3, "Exclude interruptions and events at the upper range boundary")
        let partial = exact.buckets(in: nine.addingTimeInterval(19 * 60)...nine.addingTimeInterval(55 * 60), calendar: calendar)
        expect(ActivityHistory.total(partial.map { $0.totals }).completed == 0 && ActivityHistory.total(partial.map { $0.totals }).skipped == 1, "Partial visible bins count only actions inside the window")
        let six = exact.buckets(in: today...today.addingTimeInterval(21600), calendar: calendar)
        expect(six.count == 6 && six.allSatisfy { $0.end.timeIntervalSince($0.start) == 3600 }, "Six-hour view uses hour bins")
        exact.update(DayRecord(day: HistoryDates.key(for: today, calendar: calendar), completed: 9, skipped: 2, postponed: 1, rested: 1200), now: start, calendar: calendar)
        expect(exact.hasUntimedActivity(in: today...tomorrow, calendar: calendar), "Identify daily activity with no reconstructable timestamp")
        let weekStart = calendar.date(byAdding: .day, value: -6, to: today)!
        let week = exact.buckets(in: weekStart...tomorrow, calendar: calendar)
        expect(week.count == 7 && ActivityHistory.total(week.map { $0.totals }).completed == 9, "Seven-day graph preserves all original daily totals")
        let reloadedActions = try! JSONDecoder().decode(ActivityHistory.self, from: JSONEncoder().encode(exact))
        expect(reloadedActions == exact && reloadedActions.actions.count == 2, "Timed future actions persist without fake break sessions")
        exact.prune(now: calendar.date(byAdding: .day, value: 30, to: start)!, calendar: calendar)
        expect(exact.actions.isEmpty && exact.sessions.isEmpty, "Timed actions obey 30-day retention")
        let fall = HistoryDates.date(for: "2026-11-01", calendar: calendar)!
        let afterFall = calendar.date(byAdding: .day, value: 1, to: fall)!
        let fallBins = ActivityHistory().buckets(in: fall...afterFall, calendar: calendar)
        expect(fallBins.count == 25 && Set(fallBins.map { $0.id }).count == 25, "Repeated daylight-saving hours retain distinct real-time buckets")
        var continuous = ActivityViewport(now: start, calendar: calendar, span: 21600)
        continuous.move(to: today.addingTimeInterval(12 * 3600))
        let anchor = continuous.range.lowerBound.addingTimeInterval(continuous.span * 0.2)
        continuous.zoom(factor: 0.713, anchor: 0.2)
        expect(abs(continuous.span - 21600 * 0.713) < 0.001, "Zoom accepts continuous scales instead of snapping to presets")
        expect(abs(continuous.range.lowerBound.addingTimeInterval(continuous.span * 0.2).timeIntervalSince(anchor)) < 0.001, "Keep pointed time fixed during zoom")
        let priorSpan = continuous.span, priorCenter = continuous.center
        continuous.pan(fraction: 0.327)
        expect(continuous.span == priorSpan && abs(continuous.center.timeIntervalSince(priorCenter) - priorSpan * 0.327) < 0.001, "Panning shifts range continuously without changing scale")
        continuous.zoom(factor: .nan, anchor: 0.5); continuous.pan(fraction: .infinity)
        expect(continuous.span == priorSpan, "Ignore nonfinite mouse inputs")
        print("History tests passed: retention, DST, migration, exact timestamps, outcomes, interruptions, persistence, midnight boundaries, hour/quarter-hour aggregation, continuous anchored zoom and fixed-scale pan limits")
    }
}
